version: 1
id: fullhd-30p
name: Full HD 30p
priority: 50

match:
  interlaced: false
  width: 1920
  height: 1080
  fps: 29.97
  fps_tolerance: 0.05

workflow:
  - id: encode
    filter: virtualdub.encode
    config:
      preset: x264-8-aac-mp4
