version: 1
id: hdv-25i
name: HDV 1080i25
priority: 100

match:
  interlaced: true
  width: 1440
  height: 1080
  fps: 25
  fps_tolerance: 0.1
  codec: [mpeg2video]

workflow:
  - id: prepare
    filter: avisynth.profile
    config:
      profile: hdv-25i

  - id: stabilize
    filter: virtualdub.deshaker
    config:
      reuse_analysis: true
      force_analysis: false

  - id: encode
    filter: virtualdub.encode
    config:
      preset: x264-8-aac-mp4
