version: 1
id: miniavi
name: HuffYUV AVI source
priority: 50

match:
  codec: [huffyuv]

workflow:
  - id: prepare
    filter: avisynth.profile
    config:
      profile: miniavi

  - id: encode
    filter: virtualdub.encode
    config:
      preset: huffyuv
