version: 1
id: SD16_9-progressive
name: SD 16:9 progressive to Full HD 30p
priority: 80

match:
  interlaced: false
  width: 850
  height: 478

workflow:
  - id: stabilize
    filter: virtualdub.deshaker
    config: {}

  - id: final-scale
    filter: ffmpeg.zscale
    config:
      width: 1920
      height: 1080
      filter: spline36:matrixin=gbr:transferin=709:primariesin=709:matrix=709:transfer=709:primaries=709
      pixel_format: yuv422p10le
      video_codec: prores_ks
      audio_codec: pcm_s24le
      extension: .mov
      extra_args:
        - -r
        - "30"
        - -fps_mode
        - cfr
        - -profile:v
        - "3"
