version: 1
id: uhd-progressive
name: UHD progressive 25/30/50/60p
priority: 80

match:
  interlaced: false
  width: 3840
  height: 2160

workflow:
  - id: stabilize
    filter: virtualdub.deshaker
    config: {}
