package virtualdub

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type Job struct {
	FileIndex     int
	InputPath     string
	OutputPath    string
	LogPath       string
	ReuseAnalysis bool
	ForceAnalysis bool
	Deshaker      *DeshakerTemplate
	Codec         *CodecPreset
}

type JobsBuilder struct {
	Pather *PathConverter
}

func (b JobsBuilder) Write(filename string, jobs []Job) (int, error) {
	jobCount := 0
	for _, job := range jobs {
		if analysisRequired(job) {
			jobCount++
		}
		jobCount++
	}

	var output strings.Builder
	fmt.Fprintln(&output, "// VirtualDub job list (Sylia script format)")
	fmt.Fprintln(&output, "// Generated by MediaLang")
	fmt.Fprintln(&output, "// $signature 0 1")
	fmt.Fprintf(&output, "// $numjobs %d\n//\n", jobCount)

	number := 1
	for _, job := range jobs {
		input, err := b.Pather.ToWindowsPath(job.InputPath)
		if err != nil {
			return 0, err
		}
		outputPath, err := b.Pather.ToWindowsPath(job.OutputPath)
		if err != nil {
			return 0, err
		}
		logPath, err := b.Pather.ToWindowsPath(job.LogPath)
		if err != nil {
			return 0, err
		}
		values := map[string]string{
			"InputPath":  escapeSylia(input),
			"OutputPath": escapeSylia(outputPath),
			"LogPath":    escapeSylia(logPath),
		}

		if analysisRequired(job) {
			writeJobHeader(&output, number, input, "")
			writeOpen(&output, input)
			output.WriteString(expand(job.Deshaker.AnalysisScript, values))
			ensureNewline(&output)
			fmt.Fprintln(&output, "VirtualDub.RunNullVideoPass();")
			writeClose(&output)
			number++
		}

		writeJobHeader(&output, number, input, outputPath)
		writeOpen(&output, input)
		if job.Deshaker != nil {
			output.WriteString(expand(job.Deshaker.RenderScript, values))
			ensureNewline(&output)
		}
		output.WriteString(expand(job.Codec.ContainerScript, values))
		ensureNewline(&output)
		output.WriteString(expand(job.Codec.VideoScript, values))
		ensureNewline(&output)
		output.WriteString(expand(job.Codec.AudioScript, values))
		ensureNewline(&output)
		output.WriteString(expand(job.Codec.SaveScript, values))
		ensureNewline(&output)
		writeClose(&output)
		number++
	}
	fmt.Fprintln(&output, "//--------------------------------------------------")
	fmt.Fprintln(&output, "// $done")

	if err := os.MkdirAll(filepath.Dir(filename), 0o755); err != nil {
		return 0, fmt.Errorf("create VirtualDub work directory: %w", err)
	}
	if err := os.WriteFile(filename, []byte(output.String()), 0o644); err != nil {
		return 0, fmt.Errorf("write VirtualDub jobs file %q: %w", filename, err)
	}
	return jobCount, nil
}

func analysisRequired(job Job) bool {
	if job.Deshaker == nil {
		return false
	}
	if job.ForceAnalysis {
		return true
	}
	if !job.ReuseAnalysis {
		return true
	}
	_, err := os.Stat(job.LogPath)
	return err != nil
}

func writeJobHeader(output *strings.Builder, number int, input, target string) {
	fmt.Fprintln(output, "//--------------------------------------------------")
	fmt.Fprintf(output, "// $job \"Job %d\"\n", number)
	fmt.Fprintln(output, "// $data \"\"")
	fmt.Fprintf(output, "// $input \"%s\"\n", escapeSylia(input))
	fmt.Fprintf(output, "// $output \"%s\"\n", escapeSylia(target))
	fmt.Fprintln(output, "// $state 0")
	fmt.Fprintln(output, "// $script")
}

func writeOpen(output *strings.Builder, input string) {
	fmt.Fprintf(output, "VirtualDub.Open(\"%s\",\"\",0);\n", escapeSylia(input))
}

func writeClose(output *strings.Builder) {
	fmt.Fprintln(output, "VirtualDub.Close();")
	fmt.Fprintln(output, "// $endjob")
}

func expand(script string, values map[string]string) string {
	for key, value := range values {
		script = strings.ReplaceAll(script, "{{."+key+"}}", value)
	}
	return script
}

func escapeSylia(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	return strings.ReplaceAll(value, `"`, `\"`)
}

func ensureNewline(output *strings.Builder) {
	if output.Len() > 0 {
		value := output.String()
		if value[len(value)-1] != '\n' {
			output.WriteByte('\n')
		}
	}
}
